<?php
function emoticons($text) {
    $icons = array(
            ':)'    =>  ' <img src="dist/img/Emojis/smile.png" alt="smile" class="icon_smile" height="20" width="20" /> ',
            ':smile:'    =>  ' <img src="dist/img/Emojis/smile.png" alt="smile" class="icon_smile" height="20" width="20" /> ',
            ':D'    =>  ' <img src="dist/img/Emojis/smile2.png" alt="smile" class="icon_laugh" height="20" width="20" /> ',
            ':d'    =>  ' <img src="dist/img/Emojis/smile2.png" alt="smile" class="icon_laugh" height="20" width="20" /> ',
            ':smile2:'    =>  ' <img src="dist/img/Emojis/smile2.png" alt="smile" class="icon_smile" height="20" width="20" /> ',
            ':alien2:'    =>  ' <img src="dist/img/Emojis/alien2.png" alt="alien2" class="" height="20" width="20" /> ',
            ':P'    =>  ' <img src="dist/img/Emojis/tounge.png" alt="tounge" class="icon_tounge" height="20" width="20" /> ',
            ':p'    =>  ' <img src="dist/img/Emojis/tounge.png" alt="tounge" class="icon_tounge" height="20" width="20" /> ',
            ':tounge:'    =>  ' <img src="dist/img/Emojis/tounge.png" alt="tounge" class="icon_tounge" height="20" width="20" /> ',
            ';)'    =>  ' <img src="dist/img/Emojis/wink.png" alt="wink" class="icon_wink" height="20" width="20" /> ',
            ':wink:'    =>  ' <img src="dist/img/Emojis/wink.png" alt="wink" class="icon_wink" height="20" width="20" /> ',
            ':@'    =>  ' <img src="dist/img/Emojis/angry.png" alt="angry" class="icon_wink" height="20" width="20" /> ',
            ':angry:'    =>  ' <img src="dist/img/Emojis/angry.png" alt="angry" class="icon_wink" height="20" width="20" /> ',
            ':('    =>  ' <img src="dist/img/Emojis/sad.png" alt="sad face" class="icon_sad" height="20" width="20" /> ',
            ':sad:'    =>  ' <img src="dist/img/Emojis/sad.png" alt="sad face" class="icon_sad" height="20" width="20" /> ',
            ':o'    =>  ' <img src="dist/img/Emojis/shock.png" alt="shock" class="icon_shock" height="20" width="20" /> ',
            ':O'    =>  ' <img src="dist/img/Emojis/shock.png" alt="shock" class="icon_shock" height="20" width="20" /> ',
            ':shock:'    =>  ' <img src="dist/img/Emojis/shock.png" alt="shock" class="icon_shock" height="20" width="20" /> ',
			':|'    =>  ' <img src="dist/img/Emojis/straight.png" alt="straight face" class="icon_straight" height="20" width="20" /> ',
            ':straight:'    =>  ' <img src="dist/img/Emojis/straight.png" alt="straight face" class="icon_straight" height="20" width="20" /> ',
            ':poop:'   =>  ' <img src="dist/img/Emojis/poop.png" alt="poop face" class="icon_straight" height="20" width="20" /> ',
            ':ghost:'   =>  ' <img src="dist/img/Emojis/ghost.png" alt="Ghost face" class="icon_straight" height="20" width="20" /> ',
            ':frog:'   =>  ' <img src="dist/img/Emojis/frog.png" alt="Frog face" class="icon_straight" height="20" width="22" /> ',
            ':turtle:'   =>  ' <img src="dist/img/Emojis/turtle.png" alt="Frog face" class="icon_straight" height="20" width="20" /> ',
            ':broken:'   =>  ' <img src="dist/img/Emojis/broken.png" alt="Frog face" class="icon_straight" height="20" width="20" /> ',
            ':praying:'   =>  ' <img src="dist/img/Emojis/praying.png" alt="Frog face" class="icon_straight" height="20" width="20" /> ',
            ':thumpsup:'   =>  ' <img src="dist/img/Emojis/ThumbsUp.png" alt="ThumbsUp" class="icon_straight" height="20" width="20" /> ',
            ':thumpsdown:'   =>  ' <img src="dist/img/Emojis/ThumbsDown.png" alt="ThumbsDown" class="icon_straight" height="20" width="20" /> ',
            ':fuck:'   =>  ' <img src="dist/img/Emojis/fuck.png" alt="fuck" class="icon_straight" height="20" width="20" /> ',
            ':wut:'   =>  ' <img src="dist/img/Emojis/wut.webp" alt="fuck" class="icon_straight" height="20" width="20" /> ',
            ':doggy:'   =>  ' <img src="dist/img/Emojis/doggy.gif" alt="doggy" class="icon_straight" height="30" width="20" /> ',
			':/'    =>  ' <img src="dist/img/Emojis/confused.png" alt="confused face" class="icon_confused" height="20" width="20" /> ',
            ':confused:'    =>  ' <img src="dist/img/Emojis/confused.png" alt="confused face" class="icon_confused" height="20" width="20" />',
			':loader:'    =>  ' <img src="dist/img/Emojis/ajax-loader.gif" alt="loader" class="icon_smile" height="20" width="20" /> ',
            ':alien1:'    =>  ' <img src="dist/img/Emojis/alien1.png" alt="alien1" class="icon_smile" height="20" width="20" /> ',
            ':angel:'     =>  ' <img src="dist/img/Emojis/angel.png" alt="angel" class="icon_laugh" height="20" width="20" /> ',
            ':angry:'    =>  ' <img src="dist/img/Emojis/angry.png" alt="angry" class="icon_laugh" height="20" width="20" /> ',
            ':annoyed:'    =>  ' <img src="dist/img/Emojis/annoyed.png" alt="annoyed" class="icon_smile" height="20" width="20" /> ',
            ':blanco:'    =>  ' <img src="dist/img/Emojis/blanco.png" alt="blanco" class="" height="20" width="20" /> ',
            ':blush:'    =>  ' <img src="dist/img/Emojis/blush.png" alt="blush" class="icon_tounge" height="20" width="20" /> ',
            ':boring:'    =>  ' <img src="dist/img/Emojis/boring.png" alt="boring" class="icon_tounge" height="20" width="20" /> ',
            ':brb:'    =>  ' <img src="dist/img/Emojis/brb.png" alt="brb" class="icon_tounge" height="20" width="20" /> ',
            ':busy:'    =>  ' <img src="dist/img/Emojis/busy.png" alt="busy" class="icon_wink" height="20" width="20" /> ',
            ':cellphone:'    =>  ' <img src="dist/img/Emojis/cellphone.png" alt="cellphone" class="icon_wink" height="20" width="20" /> ',
            ':clock:'    =>  ' <img src="dist/img/Emojis/clock.png" alt="clock" class="icon_wink" height="20" width="20" /> ',
            ':cool:'    =>  ' <img src="dist/img/Emojis/cool.png" alt="cool" class="icon_wink" height="20" width="20" /> ',
            ':crazy:'    =>  ' <img src="dist/img/Emojis/crazy.png" alt="crazy" class="icon_sad" height="20" width="20" /> ',
            ':cry:'    =>  ' <img src="dist/img/Emojis/cry.png" alt="cry" class="icon_sad" height="20" width="20" /> ',
            ':devil:'    =>  ' <img src="dist/img/Emojis/devil.png" alt="devil" class="icon_shock" height="20" width="20" /> ',
            ':devil_laugh:'    =>  ' <img src="dist/img/Emojis/devil_laugh.png" alt="devil_laugh" class="icon_shock" height="20" width="20" /> ',
            ':dnd:'    =>  ' <img src="dist/img/Emojis/dnd.png" alt="dnd" class="icon_shock" height="20" width="20" /> ',
			':female:'    =>  ' <img src="dist/img/Emojis/female.png" alt="female" class="icon_straight" height="20" width="20" /> ',
            ':flower:'    =>  ' <img src="dist/img/Emojis/flower.png" alt="flower" class="icon_straight" height="20" width="20" /> ',
            ':fools:'   =>  ' <img src="dist/img/Emojis/fools.png" alt="fools" class="icon_straight" height="20" width="20" /> ',
            ':geek:'   =>  ' <img src="dist/img/Emojis/geek.png" alt="geek" class="icon_straight" height="20" width="20" /> ',
            ':gift:'   =>  ' <img src="dist/img/Emojis/gift.png" alt="gift" class="icon_straight" height="20" width="22" /> ',
            ':hay:'   =>  ' <img src="dist/img/Emojis/hay.png" alt="hay" class="icon_straight" height="20" width="20" /> ',
            ':ill:'   =>  ' <img src="dist/img/Emojis/ill.png" alt="ill" class="icon_straight" height="20" width="20" /> ',
            ':in_love:'   =>  ' <img src="dist/img/Emojis/in_love.png" alt="in_love" class="icon_straight" height="20" width="20" /> ',
            ':info:'   =>  ' <img src="dist/img/Emojis/info.png" alt="info" class="icon_straight" height="20" width="20" /> ',
            ':kissy:'   =>  ' <img src="dist/img/Emojis/kissy.png" alt="kissy" class="icon_straight" height="20" width="20" /> ',
            ':laugh:'   =>  ' <img src="dist/img/Emojis/laugh.png" alt="laugh" class="icon_straight" height="20" width="20" /> ',
            ':male:'   =>  ' <img src="dist/img/Emojis/male.png" alt="male" class="icon_straight" height="20" width="20" /> ',
            ':mario:'   =>  ' <img src="dist/img/Emojis/mario.png" alt="mario" class="icon_straight" height="30" width="20" /> ',
			':meow:'    =>  ' <img src="dist/img/Emojis/meow.png" alt="meow" class="icon_confused" height="20" width="20" /> ',
            ':minishock:'    =>  ' <img src="dist/img/Emojis/minishock.png" alt="minishock" class="icon_confused" height="20" width="20" />'
    );
    return strtr($text, $icons);
}
?>